CREATE DATABASE Seguro;
GO

USE Seguro;
GO

CREATE TABLE TB_VEICULO
(
	[ID]							UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[MARCA]							NVARCHAR(30) NOT NULL,
	[MODELO]						NVARCHAR(100) NOT NULL,
	[VALOR]							DECIMAL(18,2) NOT NULL
);
GO

INSERT INTO TB_VEICULO ([ID], [MARCA], [MODELO], [VALOR]) VALUES (NEWID(), 'Volkswagen', 'Gol', 20.000);
INSERT INTO TB_VEICULO ([ID], [MARCA], [MODELO], [VALOR]) VALUES (NEWID(), 'Volkswagen', 'Tiguan', 115.000);
INSERT INTO TB_VEICULO ([ID], [MARCA], [MODELO], [VALOR]) VALUES (NEWID(), 'Volkswagen', 'Jetta', 70.000);
INSERT INTO TB_VEICULO ([ID], [MARCA], [MODELO], [VALOR]) VALUES (NEWID(), 'Chevrolet', 'Onix', 35.000);
INSERT INTO TB_VEICULO ([ID], [MARCA], [MODELO], [VALOR]) VALUES (NEWID(), 'Chevrolet', 'Prisma', 24.000);
INSERT INTO TB_VEICULO ([ID], [MARCA], [MODELO], [VALOR]) VALUES (NEWID(), 'Ford', 'Fusion', 100.000);
INSERT INTO TB_VEICULO ([ID], [MARCA], [MODELO], [VALOR]) VALUES (NEWID(), 'Ford', 'Ka', 20.000);
INSERT INTO TB_VEICULO ([ID], [MARCA], [MODELO], [VALOR]) VALUES (NEWID(), 'Ford', 'Ranger', 200.000);

CREATE TABLE TB_SEGURADO
(
	[ID]							UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[NOME]							NVARCHAR(100) NOT NULL,
	[CPF]							NVARCHAR(14) NOT NULL,
	[IDADE]							NVARCHAR(100) NOT NULL,
);
GO
