
IF(EXISTS(SELECT * FROM SYS.DATABASES WHERE NAME = 'DIVERSOS_TESTES'))
	USE master;
	GO

	DROP DATABASE [DIVERSOS_TESTES];
GO

CREATE DATABASE [DIVERSOS_TESTES];
GO

USE [DIVERSOS_TESTES];
GO

CREATE SCHEMA SEGURO  
    CREATE TABLE TB_VEICULO
	(
		ID								UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
		MARCA							NVARCHAR(50) NOT NULL,
		MODELO							NVARCHAR(50) NOT NULL,
		VALOR							DECIMAL(18, 2) NOT NULL
	)

	CREATE TABLE TB_SEGURADO
	(
		ID								UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
		NOME							NVARCHAR(50) NOT NULL,
		CPF								NVARCHAR(50) NOT NULL
	)

	CREATE TABLE TB_SEGURADORA
	(
		ID								UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
		NOME							NVARCHAR(50) NOT NULL,
		MARGEM_SEGURANCA				DECIMAL(3, 2) NOT NULL,
		LUCRO							DECIMAL(3, 2) NOT NULL
	)

	CREATE TABLE TB_SEGURO
	(
		ID								UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
		TB_SEGURADORA_ID				UNIQUEIDENTIFIER NOT NULL,
		TB_VEICULO_ID					UNIQUEIDENTIFIER NOT NULL,
		TB_SEGURADO_ID					UNIQUEIDENTIFIER NOT NULL,
		VALOR_FINAL						DECIMAL(18, 2) NOT NULL,
		FOREIGN KEY (TB_SEGURADORA_ID)	REFERENCES TB_SEGURADORA(ID),
		FOREIGN KEY (TB_VEICULO_ID)		REFERENCES TB_VEICULO(ID),
		FOREIGN KEY (TB_SEGURADO_ID)	REFERENCES TB_SEGURADO(ID),
	)


GO



INSERT INTO SEGURO.TB_SEGURADORA (ID, NOME, MARGEM_SEGURANCA, LUCRO) VALUES(NEWID(), 'WILLIAN SEGURO', 0.03, 0.05);
INSERT INTO SEGURO.TB_SEGURADORA (ID, NOME, MARGEM_SEGURANCA, LUCRO) VALUES(NEWID(), 'BARRETO SEGURO', 0.05, 0.2);

